apiVersion: apps/v1
kind: Deployment
metadata:
  name: johnapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: johnapp
  template:
    metadata:
      labels:
        app: johnapp
    spec:
      containers:
      - name: johnapp
        image: 995076765584.dkr.ecr.us-east-2.amazonaws.com/johnappimage
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: johnapp
    k8s-app: johnapp
  name: johnapp
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: johnapp
